@baseUrl = http://localhost:3000
@token = 

### ========================
### USUÁRIOS
### ========================

### Criar usuário
POST {{baseUrl}}/user/create
Content-Type: application/json

{
  "name": "Ronaldo Teste",
  "email": "ronaldo@teste.com",
  "password": "12345678"
}


### Actualizar
PATCH  {{baseUrl}}/user/update/68de9c8b38d410e0b25a2709
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU5YzhiMzhkNDEwZTBiMjVhMjcwOSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImlhdCI6MTc1OTkyMTk2NywiZXhwIjoxNzYwNTI2NzY3fQ.ebPD_4AcPDlZDW7yRQdEJx9f0-WXyMENJZ5Ib5iqZ7g
Content-Type: application/json

{
  "name": "Ronaldo Bernardo",
  "email": "ronaldo@gmail.com",
  "password": "12345678"
}





### Listar usuários (precisa TOKEN se for admin)
GET {{baseUrl}}/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU5YzhiMzhkNDEwZTBiMjVhMjcwOSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImlhdCI6MTc2MDYxMTg5MiwiZXhwIjoxNzYxMjE2NjkyfQ.bCTQerA1k5A91jHiKn-uUtNgh1ec3BQdcZ6cscveBzM


### ========================
### AUTENTICAÇÃO
### ========================

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
 "email": "ronaldo@teste.com",
  "password": "12345678"
}

###
> {% client.global.set("token", response.body.token); %}



### ========================
### LICENÇAS (precisam de TOKEN)
### ========================


### Criar licença
POST {{baseUrl}}/license/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTAxMDgxNjkzZmFlYWNiMzQxODM5MSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTUxNTgxOCwiZXhwIjoxNzYwMTIwNjE4fQ.h0DsghVDEHMWdNWPG2NbhGFxB49nkfaDodMy1x9RUF4
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="company"

Empresa Pavlov
--WebAppBoundary
Content-Disposition: form-data; name="type"

Origem
--WebAppBoundary
Content-Disposition: form-data; name="location"

Viana
--WebAppBoundary
Content-Disposition: form-data; name="validUntil"

2025-12-31
--WebAppBoundary
Content-Disposition: form-data; name="document"; filename="exemplar.pdf"
Content-Type: application/pdf

< ./exemplar.pdf
--WebAppBoundary--
### Listar todas licenças
GET {{baseUrl}}/license/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU5ZjMzNzc1NDZkNmRkYzI5MTY3MCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTUxNDUyNywiZXhwIjoxNzYwMTE5MzI3fQ.SCJ17Ee_3teOU4CEC6Vg5ZCU9YwT9e-qbu12LM-C-D4



### Buscar licença por ID
GET {{baseUrl}}/license/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU5YzhiMzhkNDEwZTBiMjVhMjcwOSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImlhdCI6MTc2MDYxMTg5MiwiZXhwIjoxNzYxMjE2NjkyfQ.bCTQerA1k5A91jHiKn-uUtNgh1ec3BQdcZ6cscveBzM
### Atualizar licença
PATCH  {{baseUrl}}/user/update/admin/68e01081693faeacb3418391
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU5YzhiMzhkNDEwZTBiMjVhMjcwOSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImlhdCI6MTc2MDYxMTg5MiwiZXhwIjoxNzYxMjE2NjkyfQ.bCTQerA1k5A91jHiKn-uUtNgh1ec3BQdcZ6cscveBzM

{
  "isActive": false
}

### Deletar licença
DELETE {{baseUrl}}/user/delete/68de9f3377546d6ddc291670
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGU5YzhiMzhkNDEwZTBiMjVhMjcwOSIsInJvbGUiOiJzdXBlci1hZG1pbiIsImlhdCI6MTc2MDYxMTg5MiwiZXhwIjoxNzYxMjE2NjkyfQ.bCTQerA1k5A91jHiKn-uUtNgh1ec3BQdcZ6cscveBzM


### ========================
### VALIDAÇÃO (pública, sem TOKEN)
### ========================

### Validar licença publicamente
GET {{baseUrl}}/license/validate/LIC-1758124770228


### Testar Qr Base64
GET {{baseUrl}}/test/qr-base64?text=L-2500006110

### Testar Qr Base64
GET {{baseUrl}}/test/qr-file?text=L-2500006110

### Testar Qr text
GET {{baseUrl}}/test/qr-text?text=L-2500006110

###Testes
GET {{baseUrl}}/license/dowload/68c9e64116e12e56d8096337
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Y2MxNmU2OWY1NjUyYjlmYzkyZjNjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1ODIwNTY3MCwiZXhwIjoxNzU4ODEwNDcwfQ.KRlQolocMaiUzM_DG_D4zzZzhgtvaWn-edtZnFBSxrw
###
### ========================
### ESTATÍSTICAS (admin)
### ========================

GET {{baseUrl}}/license/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Y2MxNmU2OWY1NjUyYjlmYzkyZjNjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1ODIwNTY3MCwiZXhwIjoxNzU4ODEwNDcwfQ.KRlQolocMaiUzM_DG_D4zzZzhgtvaWn-edtZnFBSxrw
